- hosts: localhost
  tasks:
  - name: Deploy the application
    command: kubectl apply -f deploy-pods.yml

  - name: create a service
    command: kubectl apply -f service.yml

  - name: create a ingres nginx
    command: kubectl apply -f ingres-nginx.yml
