apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: jebro/webstore:1.0:1.0
        ports:
        - containerPort: 8080
